
// Objective-C API for talking to the following Go packages
//
//	github.com/privacybydesign/irmamobile/irmagobridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Irmagobridge_FRAMEWORK_H__
#define __Irmagobridge_FRAMEWORK_H__

#include "Irmagobridge.objc.h"
#include "Universe.objc.h"

#endif
