// Objective-C API for talking to github.com/privacybydesign/irmamobile/irmagobridge Go package.
//   gobind -lang=objc github.com/privacybydesign/irmamobile/irmagobridge
//
// File is generated by gobind. Do not edit.

#ifndef __Irmagobridge_H__
#define __Irmagobridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class IrmagobridgeWrappedConfiguration;
@class IrmagobridgeWrappedCredentialType;
@protocol IrmagobridgeIrmaMobileBridge;
@class IrmagobridgeIrmaMobileBridge;
@protocol IrmagobridgeSigner;
@class IrmagobridgeSigner;

@protocol IrmagobridgeIrmaMobileBridge <NSObject>
- (void)debugLog:(NSString* _Nullable)message;
- (void)dispatchFromGo:(NSString* _Nullable)name payload:(NSString* _Nullable)payload;
@end

@protocol IrmagobridgeSigner <NSObject>
- (NSData* _Nullable)publicKey:(NSString* _Nullable)keyname error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)sign:(NSString* _Nullable)keyname msg:(NSData* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * needed to inject logo into issuers
 */
@interface IrmagobridgeWrappedConfiguration : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field WrappedConfiguration.SchemeManagers with unsupported type: map[github.com/privacybydesign/irmago.SchemeManagerIdentifier]*github.com/privacybydesign/irmago.SchemeManager

// skipped field WrappedConfiguration.Issuers with unsupported type: map[github.com/privacybydesign/irmago.IssuerIdentifier]*github.com/privacybydesign/irmago.Issuer

// skipped field WrappedConfiguration.CredentialTypes with unsupported type: map[github.com/privacybydesign/irmago.CredentialTypeIdentifier]*github.com/privacybydesign/irmago.CredentialType

// skipped field WrappedConfiguration.AttributeTypes with unsupported type: map[github.com/privacybydesign/irmago.AttributeTypeIdentifier]*github.com/privacybydesign/irmago.AttributeType

// skipped field WrappedConfiguration.RequestorSchemes with unsupported type: map[github.com/privacybydesign/irmago.RequestorSchemeIdentifier]*github.com/privacybydesign/irmago.RequestorScheme

// skipped field WrappedConfiguration.Requestors with unsupported type: map[string]*github.com/privacybydesign/irmago.RequestorInfo

// skipped field WrappedConfiguration.IssueWizards with unsupported type: map[github.com/privacybydesign/irmago.IssueWizardIdentifier]*github.com/privacybydesign/irmago.IssueWizard

// skipped field WrappedConfiguration.DisabledRequestorSchemes with unsupported type: map[github.com/privacybydesign/irmago.RequestorSchemeIdentifier]*github.com/privacybydesign/irmago.SchemeManagerError

// skipped field WrappedConfiguration.DisabledSchemeManagers with unsupported type: map[github.com/privacybydesign/irmago.SchemeManagerIdentifier]*github.com/privacybydesign/irmago.SchemeManagerError

// skipped field WrappedConfiguration.UpdateListeners with unsupported type: []github.com/privacybydesign/irmago.ConfigurationListener

@property (nonatomic) NSString* _Nonnull path;
// skipped field WrappedConfiguration.PrivateKeys with unsupported type: github.com/privacybydesign/irmago.PrivateKeyRing

// skipped field WrappedConfiguration.Revocation with unsupported type: *github.com/privacybydesign/irmago.RevocationStorage

// skipped field WrappedConfiguration.Scheduler with unsupported type: *github.com/go-co-op/gocron.Scheduler

// skipped field WrappedConfiguration.Warnings with unsupported type: []string

- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
@end

@interface IrmagobridgeWrappedCredentialType : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull logo;
// skipped field WrappedCredentialType.CredentialType with unsupported type: github.com/privacybydesign/irmago.CredentialType

// skipped method WrappedCredentialType.AttributeType with unsupported parameter or return types

// skipped method WrappedCredentialType.ContainsAttribute with unsupported parameter or return types

// skipped method WrappedCredentialType.Identifier with unsupported parameter or return types

// skipped method WrappedCredentialType.IndexOf with unsupported parameter or return types

// skipped method WrappedCredentialType.IssuerIdentifier with unsupported parameter or return types

// skipped method WrappedCredentialType.RandomBlindAttributeIndices with unsupported parameter or return types

// skipped method WrappedCredentialType.RandomBlindAttributeNames with unsupported parameter or return types

- (BOOL)revocationSupported;
// skipped method WrappedCredentialType.SchemeManagerIdentifier with unsupported parameter or return types

@end

/**
 * DispatchFromNative receives events from the Android / iOS native side
 */
FOUNDATION_EXPORT void IrmagobridgeDispatchFromNative(NSString* _Nullable eventName, NSString* _Nullable payloadString);

/**
 * Prestart is invoked only on Android in MainActivity's onCreate, to initialize
the Go binding at the earliest moment, instead of inside the Flutter plugin
 */
FOUNDATION_EXPORT void IrmagobridgePrestart(void);

/**
 * Start is invoked from the native side, when the app starts
 */
FOUNDATION_EXPORT void IrmagobridgeStart(id<IrmagobridgeIrmaMobileBridge> _Nullable givenBridge, NSString* _Nullable appDataPath, NSString* _Nullable assetsPath, id<IrmagobridgeSigner> _Nullable signer, NSData* _Nullable aesKey);

FOUNDATION_EXPORT void IrmagobridgeStop(void);

@class IrmagobridgeIrmaMobileBridge;

@class IrmagobridgeSigner;

/**
 * IrmaMobileBridge is the iOS or Android native component that is used for message passing
 */
@interface IrmagobridgeIrmaMobileBridge : NSObject <goSeqRefInterface, IrmagobridgeIrmaMobileBridge> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)debugLog:(NSString* _Nullable)message;
- (void)dispatchFromGo:(NSString* _Nullable)name payload:(NSString* _Nullable)payload;
@end

@interface IrmagobridgeSigner : NSObject <goSeqRefInterface, IrmagobridgeSigner> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSData* _Nullable)publicKey:(NSString* _Nullable)keyname error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)sign:(NSString* _Nullable)keyname msg:(NSData* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
@end

#endif
