#!/usr/bin/env bash
set -euxo pipefail

# =============================================================================
# fdroid_build.sh — Build the F-Droid APK the way the F-Droid buildserver does.
#
# This is the `build:` step of the org.irmacard.cardemu recipe in
# https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.irmacard.cardemu.yml
# It used to be inlined there, duplicated per release and impossible to test
# without a full buildserver run. It lives here so the recipe can call it and so
# a change to the build only needs a change in this repository.
#
# Why this exists at all: bind_go.sh normally downloads prebuilt static
# libraries from GitHub releases -- SQLCipher + OpenSSL, and the zero-knowledge
# prover. F-Droid does not allow prebuilt binaries, so this script cross-compiles
# them from source (from the OpenSSL, sqlcipher and longfellow-zk srclibs) into
# build/sqlcipher-prebuilt/android/<abi> and build/longfellow-prebuilt/android/
# <abi>, which is exactly where bind_go.sh looks. Finding them there, bind_go.sh
# skips the download and links against them. The prover is the one that can be
# absent -- see BUILD_PROVER below -- and ALLOW_PREBUILT_DOWNLOADS=0 is what
# stops bind_go.sh filling that gap from the network.
#
# Usage:
#   FLUTTER_DIR=... GO_SRC_DIR=... OPENSSL_SRC_DIR=... SQLCIPHER_SRC_DIR=... \
#     ANDROID_NDK_HOME=... ./yivi_fdroid/fdroid_build.sh
#
# In the F-Droid recipe those values are srclib/NDK placeholders, which only
# expand inside the .yml, so the recipe has to pass them in:
#
#   build:
#     - FLUTTER_DIR=$$flutter$$ GO_SRC_DIR=$$go$$ OPENSSL_SRC_DIR=$$OpenSSL$$
#       SQLCIPHER_SRC_DIR=$$sqlcipher$$ ANDROID_NDK_HOME=$$NDK$$
#       LONGFELLOW_SRC_DIR=$$longfellow-zk$$ LONGFELLOW_GO_DIR=$$longfellow-go$$
#       ZSTD_SRC_DIR=$$zstd$$ GTEST_SRC_DIR=$$googletest$$
#       BENCHMARK_SRC_DIR=$$benchmark$$
#       bash fdroid_build.sh
#
# with the recipe's srclibs list extended to (pins chosen to match what
# longfellow-go's Dockerfile builds and what its measurements were taken on):
#
#   - longfellow-zk@61a8a735964d1b22bccf79bf14ef6767249cdf92
#   - longfellow-go@18433b1932e85cdea2889755376a2cf5122a44e6
#     (keep this the SAME commit as yivi_core/go.mod's module pin — the module
#     carries the binding that calls set_mdoc_log_level, this srclib carries
#     the patch that provides it, and they drift independently if pinned apart)
#   - zstd@v1.5.6
#   - googletest@v1.15.2
#   - benchmark@v1.9.1
#
# longfellow-zk, googletest and benchmark will need srclib definitions
# contributed to fdroiddata if none exist yet; each is three lines naming a
# public git URL.
#
# On the circuits: the eight circuit files under yivi_core/irmagobridge/
# zkcircuits/ are Apache-2.0 data generated by upstream's own generator, with
# provenance and published hashes in that directory's README. They cannot be
# regenerated here because generate_circuit emits only the newest revision,
# while deployed readers negotiate older ones. The app recomputes each file's
# circuit_id at load and refuses a mismatch, so their integrity is enforced at
# run time, not merely at review time. The nearest F-Droid precedent is
# Tesseract traineddata in main-repo OCR apps: Apache-2.0 functional data,
# pinned by hash, not rebuilt from source.
#
# Required environment:
#   FLUTTER_DIR        Flutter SDK checkout ($$flutter$$)
#   GO_SRC_DIR         Go source checkout, built from source here ($$go$$)
#   OPENSSL_SRC_DIR    OpenSSL source checkout ($$OpenSSL$$)
#   SQLCIPHER_SRC_DIR  SQLCipher source checkout ($$sqlcipher$$)
#   ANDROID_NDK_HOME   Android NDK ($$NDK$$)
#
# Optional environment — the zero-knowledge prover, all five or none:
#   LONGFELLOW_SRC_DIR    longfellow-zk checkout, pin 61a8a735964d1b22bccf79bf14ef6767249cdf92
#   LONGFELLOW_GO_DIR     longfellow-go checkout; supplies patches/ only, the Go
#                         binding itself arrives as an ordinary module dependency
#   ZSTD_SRC_DIR          zstd checkout, pin v1.5.6
#   GTEST_SRC_DIR         googletest checkout, pin v1.15.2
#   BENCHMARK_SRC_DIR     benchmark checkout, pin v1.9.1
#
# Unset, the APK builds without a prover and the wallet answers every request
# with the plain ISO mDoc presentation, which AV Annex A §A.6 defines as the
# path for exactly such a device. bind_go.sh decides per ABI by looking for
# libmdoc_static.a, so the prover stays an addition rather than a dependency.
#
# googletest and benchmark are build inputs, not test baggage to trim:
# longfellow's CMake find_package()s both unconditionally at CONFIGURE time, so
# the project will not configure without them even though nothing a wallet
# links needs either. Upstream's own android.sh builds them for the same reason.
#
# Also needed, and provided by the recipe's `sudo:` and `prebuild:` steps:
#   - build-essential, tcl, unzip and a bootstrap Go (to run go's make.bash)
#   - cmake (for the prover's dependency set; Debian's is fine)
#   - `flutter pub get` already run in this directory
# =============================================================================

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$APP_DIR/.." && pwd)"

# F-Droid buildservers are Debian x86_64; the NDK ships one toolchain per host.
NDK_HOST_TAG="linux-x86_64"

# Minimum supported Android API level. Must match the -androidapi passed to
# gomobile in bind_go.sh, otherwise the static libs and libgojni.so disagree.
ANDROID_API=26

# The ABIs bind_go.sh builds, so every one of them needs its own static libs.
ABIS=(arm64-v8a armeabi-v7a x86_64)

# Where bind_go.sh expects to find the static libs.
PREBUILT_DIR="$ROOT/build/sqlcipher-prebuilt/android"

# Scratch copies of the srclibs. We build out of a copy because both configure
# scripts write into their source tree, and a srclib is shared between builds.
OPENSSL_BUILD_DIR="$ROOT/bo"
SQLCIPHER_BUILD_DIR="$ROOT/bs"

# The prover's scratch tree. longfellow-zk is built out of a copy for the same
# reason OpenSSL is, plus one of its own: the memory and logging patches from
# longfellow-go/patches/ are applied to the copy, and a srclib must never be
# modified in place because it is shared between builds.
LONGFELLOW_BUILD_DIR="$ROOT/bl"

# Where bind_go.sh looks for the prover, per ABI. Finding libmdoc_static.a
# there, it adds the include/link flags and the `longfellow` build tag for that
# ABI; not finding it, it builds the bridge without a prover. Same contract as
# PREBUILT_DIR above, same reason.
LONGFELLOW_PREBUILT_DIR="$ROOT/build/longfellow-prebuilt/android"

require_env() {
  local missing=()
  local name
  for name in "$@"; do
    if [ -z "${!name:-}" ]; then
      missing+=("$name")
    fi
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    echo "ERROR: missing required environment variables: ${missing[*]}" >&2
    echo "See the header of $0 for what each one should point at." >&2
    exit 1
  fi
}

require_env FLUTTER_DIR GO_SRC_DIR OPENSSL_SRC_DIR SQLCIPHER_SRC_DIR ANDROID_NDK_HOME

# The prover inputs are all-or-none. A partial set would not fail here — the
# longfellow build would fail somewhere in the middle of the third ABI with an
# error naming a missing directory, long after the cause.
ZK_VARS=(LONGFELLOW_SRC_DIR LONGFELLOW_GO_DIR ZSTD_SRC_DIR GTEST_SRC_DIR BENCHMARK_SRC_DIR)
ZK_SET=0
for name in "${ZK_VARS[@]}"; do
  if [ -n "${!name:-}" ]; then ZK_SET=$((ZK_SET + 1)); fi
done
if [ "$ZK_SET" -ne 0 ] && [ "$ZK_SET" -ne "${#ZK_VARS[@]}" ]; then
  echo "ERROR: the zero-knowledge prover needs all of ${ZK_VARS[*]} or none; $ZK_SET of ${#ZK_VARS[@]} are set." >&2
  exit 1
fi
BUILD_PROVER=$([ "$ZK_SET" -eq "${#ZK_VARS[@]}" ] && echo 1 || echo 0)

# --- Per-ABI toolchain mapping ---------------------------------------------
# Every ABI names itself three different ways: the NDK clang wrapper prefix, the
# autoconf --host value and OpenSSL's own target name. They are not
# interchangeable, and armeabi-v7a is the one where all three differ.

abi_triple() {
  case "$1" in
    arm64-v8a)   echo "aarch64-linux-android" ;;
    armeabi-v7a) echo "armv7a-linux-androideabi" ;;
    x86_64)      echo "x86_64-linux-android" ;;
    *) echo "Unknown ABI: $1" >&2; exit 1 ;;
  esac
}

abi_host_triple() {
  case "$1" in
    arm64-v8a)   echo "aarch64-linux-android" ;;
    armeabi-v7a) echo "arm-linux-androideabi" ;;
    x86_64)      echo "x86_64-linux-android" ;;
    *) echo "Unknown ABI: $1" >&2; exit 1 ;;
  esac
}

abi_openssl_target() {
  case "$1" in
    arm64-v8a)   echo "android-arm64" ;;
    armeabi-v7a) echo "android-arm" ;;
    x86_64)      echo "android-x86_64" ;;
    *) echo "Unknown ABI: $1" >&2; exit 1 ;;
  esac
}

# =============================================================================
# Build Go from source. F-Droid cannot ship the official toolchain, so the go
# srclib is a source checkout that make.bash turns into a usable toolchain,
# bootstrapped by the distro Go the recipe installs.
# =============================================================================

echo "==> Building the Go toolchain from source"
(cd "$GO_SRC_DIR/src" && ./make.bash)

export GOROOT="$GO_SRC_DIR"
export GOPATH="$APP_DIR/golang"
# Stop the toolchain from downloading a different Go than the one we just built.
export GOTOOLCHAIN=local
export PATH="$GO_SRC_DIR/bin:$GOPATH/bin:$PATH"

# gomobile and the Android Gradle plugin read both spellings, depending on version.
export ANDROID_NDK_HOME
export ANDROID_NDK_ROOT="$ANDROID_NDK_HOME"

TC="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$NDK_HOST_TAG"
export PATH="$TC/bin:$PATH"

# =============================================================================
# Cross-compile OpenSSL and SQLCipher for every ABI.
# =============================================================================

build_openssl() {
  local abi="$1" prefix="$2"
  local openssl_target
  # Assign on its own line so an unknown ABI aborts here, instead of handing
  # Configure an empty target and building for the host.
  openssl_target="$(abi_openssl_target "$abi")"
  echo "==> Building OpenSSL for $abi"

  rm -rf "$OPENSSL_BUILD_DIR"
  cp -a "$OPENSSL_SRC_DIR" "$OPENSSL_BUILD_DIR"

  (
    cd "$OPENSSL_BUILD_DIR"
    ./Configure "$openssl_target" \
      "-D__ANDROID_API__=$ANDROID_API" \
      --prefix="$prefix" \
      no-shared no-tests no-ui-console no-engine no-async
    # build_libs + install_dev: we only need libcrypto.a and its headers, not
    # the apps or the docs.
    make -j"$(nproc)" build_libs
    make install_dev
  )
}

build_sqlcipher() {
  local abi="$1" prefix="$2"
  local triple host_triple
  triple="$(abi_triple "$abi")"
  host_triple="$(abi_host_triple "$abi")"
  echo "==> Building SQLCipher for $abi"

  rm -rf "$SQLCIPHER_BUILD_DIR"
  cp -a "$SQLCIPHER_SRC_DIR" "$SQLCIPHER_BUILD_DIR"

  (
    cd "$SQLCIPHER_BUILD_DIR"
    CC="$TC/bin/${triple}${ANDROID_API}-clang" \
    AR="$TC/bin/llvm-ar" \
    RANLIB="$TC/bin/llvm-ranlib" \
    ./configure \
      --host="$host_triple" \
      --prefix="$prefix" \
      --disable-shared \
      --with-tempstore=yes \
      --disable-tcl \
      CFLAGS="-DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_TEMP_STORE=2 -DSQLITE_EXTRA_INIT=sqlcipher_extra_init -DSQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown -I$prefix/include" \
      LDFLAGS="-L$prefix/lib -lcrypto"
    make -j"$(nproc)" libsqlite3.a

    # `make install` would also install the shell and the tcl bits, so place
    # the pieces bind_go.sh needs by hand. SQLCipher's amalgamation is named
    # libsqlite3.a but the linker flag in bind_go.sh is -lsqlcipher.
    mkdir -p "$prefix/lib" "$prefix/include/sqlcipher"
    cp libsqlite3.a "$prefix/lib/libsqlcipher.a"
    cp sqlite3.h "$prefix/include/sqlite3.h"
    cp sqlite3.h "$prefix/include/sqlcipher/sqlite3.h"
  )
}

# =============================================================================
# Cross-compile the longfellow-zk prover for one ABI.
#
# Adapted from longfellow-go/scripts/build-longfellow-android.sh, which is in
# turn adapted from upstream's android.sh. The differences here are F-Droid's:
# every `git clone` becomes a srclib checkout passed in by the recipe, and the
# patch set longfellow-go carries against the pinned ref is applied first —
# those patches are what the published measurements describe (215 MB -> 165 MB
# peak RSS on the shipping circuit) and what lets the Go binding silence the
# library's logger through the C ABI instead of through a C++ shim.
#
# OpenSSL is NOT built again. build_openssl above already produced a libcrypto
# for this ABI at this API level, and longfellow needs only headers to compile
# — libmdoc_static.a is an archive, nothing links until bind_go.sh. At link
# time -lcrypto resolves from the SQLCipher prefix, which bind_go.sh always
# puts on the path; shipping a second libcrypto.a here would leave the linker
# picking whichever -L comes first, silently.
# =============================================================================

build_longfellow() {
  local abi="$1" prefix="$2" openssl_prefix="$3"
  echo "==> Building longfellow-zk for $abi"

  local cmake_android=(
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake"
    -DANDROID_ABI="$abi"
    -DANDROID_PLATFORM="android-$ANDROID_API"
    -DCMAKE_BUILD_TYPE=Release
  )
  local deps="$LONGFELLOW_BUILD_DIR/deps-$abi"
  local scratch="$LONGFELLOW_BUILD_DIR/scratch-$abi"
  mkdir -p "$deps" "$scratch"

  # googletest and benchmark configure out-of-source, so the srclibs are read
  # in place and only the build directories live in scratch.
  cmake -S "$GTEST_SRC_DIR" -B "$scratch/gtest" "${cmake_android[@]}" \
    -DCMAKE_INSTALL_PREFIX="$deps" -DBUILD_GTEST=ON -DBUILD_GMOCK=ON
  cmake --build "$scratch/gtest" --target install --parallel "$(nproc)"

  cmake -S "$BENCHMARK_SRC_DIR" -B "$scratch/benchmark" "${cmake_android[@]}" \
    -DCMAKE_INSTALL_PREFIX="$deps" \
    -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_TESTING=OFF
  cmake --build "$scratch/benchmark" --target install --parallel "$(nproc)"

  cmake -S "$ZSTD_SRC_DIR/build/cmake" -B "$scratch/zstd" "${cmake_android[@]}" \
    -DCMAKE_INSTALL_PREFIX="$deps" \
    -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_SHARED=OFF -DZSTD_BUILD_TESTS=OFF
  cmake --build "$scratch/zstd" --target install --parallel "$(nproc)"

  # Headers only; see the function header for why no libcrypto.a travels.
  mkdir -p "$deps/include"
  cp -a "$openssl_prefix/include/openssl" "$deps/include/"

  # Static archives only. The CMake dependencies above are asked for static
  # builds, but a stray .so picked up here would become a runtime dependency
  # the APK does not ship — the exact prebuilt-binary shape this script exists
  # to avoid.
  rm -f "$deps"/lib/*.so "$deps"/lib/*.so.*

  # longfellow itself builds from a patched copy. patch(1) rather than git
  # apply: the copy is not a git checkout, and patch -p1 is what the mailbox
  # files in longfellow-go/patches/ were generated to survive.
  local src="$LONGFELLOW_BUILD_DIR/longfellow-zk-$abi"
  rm -rf "$src"
  cp -a "$LONGFELLOW_SRC_DIR" "$src"
  local p
  for p in "$LONGFELLOW_GO_DIR"/patches/*.patch; do
    echo "==> applying $(basename "$p")"
    patch -p1 -d "$src" --forward --fuzz=0 < "$p"
  done

  # lib/CMakeLists.txt's Android branch hardcodes ../deps-android for both
  # includes and libraries; it knows nothing about ABIs. The symlink points it
  # at this ABI's tree. A dangling or stale link fails the compile on a missing
  # openssl/sha.h with nothing to say it looked in the wrong place.
  rm -rf "$src/deps-android"
  ln -s "$deps" "$src/deps-android"

  cmake -S "$src/lib" -B "$scratch/longfellow" "${cmake_android[@]}" \
    -DCMAKE_FIND_ROOT_PATH="$deps" -DCMAKE_PREFIX_PATH="$deps"
  cmake --build "$scratch/longfellow" --target mdoc_static --parallel "$(nproc)"

  mkdir -p "$prefix/lib"
  find "$scratch/longfellow" -name 'libmdoc_static.a' -exec cp {} "$prefix/lib/" \;
  cp "$deps/lib/libzstd.a" "$prefix/lib/"

  # The patched header, not the srclib's: patch 0001 adds set_mdoc_log_level to
  # it, and the Go binding calls that symbol unconditionally.
  mkdir -p "$LONGFELLOW_PREBUILT_DIR/include"
  cp "$src/lib/circuits/mdoc/mdoc_zk.h" "$LONGFELLOW_PREBUILT_DIR/include/"

  # Six C symbols, set_mdoc_log_level included. Its absence means the patches
  # did not take, and the failure that follows otherwise is an undefined symbol
  # deep inside gomobile's link with nothing pointing back here.
  echo "==> verifying the C ABI for $abi"
  # `|| true` because grep -c exits 1 on zero matches, and under set -e that
  # would kill the script before the error message below could name the count.
  local symbols
  symbols="$("$TC/bin/llvm-nm" --defined-only "$prefix/lib/libmdoc_static.a" 2>/dev/null \
    | grep -cE ' T (run_mdoc_prover|run_mdoc_verifier|generate_circuit|find_zk_spec|circuit_id|set_mdoc_log_level)$' || true)"
  if [ "$symbols" -ne 6 ]; then
    echo "ERROR: expected 6 exported C symbols in libmdoc_static.a for $abi, found $symbols" >&2
    exit 1
  fi
}

for ABI in "${ABIS[@]}"; do
  PREFIX="$PREBUILT_DIR/$ABI"
  build_openssl "$ABI" "$PREFIX"
  build_sqlcipher "$ABI" "$PREFIX"
  if [ "$BUILD_PROVER" = 1 ]; then
    build_longfellow "$ABI" "$LONGFELLOW_PREBUILT_DIR/$ABI" "$PREFIX"
  fi
done

# bind_go.sh passes one -I for all ABIs (the headers are identical), so give it
# a single include directory alongside the per-ABI lib directories.
echo "==> Publishing the shared include directory"
# Remove it first: `cp -a src dst` on an existing dst would nest the headers as
# include/include, which only shows up as a compile error on the second run.
rm -rf "$PREBUILT_DIR/include"
cp -a "$PREBUILT_DIR/${ABIS[0]}/include" "$PREBUILT_DIR/include"

# =============================================================================
# Build the Go bridge and the APK.
# =============================================================================

echo "==> Building the Go bridge"
(cd "$ROOT" && bash ci_scripts/install_gomobile.sh)
# Left to itself, bind_go.sh downloads SQLCipher and the prover as prebuilt
# binaries whenever it does not already find them, which is the one thing this
# build may not do. Everything it needs has been compiled from source above --
# except the prover when BUILD_PROVER is 0, and there the correct outcome is the
# no-prover build bind_go.sh falls back to, not a download. Scoped to this call
# rather than exported, so it cannot reach anything else.
(cd "$ROOT" && ALLOW_PREBUILT_DOWNLOADS=0 bash bind_go.sh android)

echo "==> Building the APK"
# Keep the pub cache inside this directory so the recipe's `scandelete:` entry
# for yivi_fdroid/.pub-cache can clean it up before the APK is scanned.
export PUB_CACHE="$APP_DIR/.pub-cache"
(cd "$APP_DIR" && "$FLUTTER_DIR/bin/flutter" build apk --flavor beta)
