name: yivi
description: "Yivi App"

# A build number cannot be reused once a build is in use on Android.
version: 7.14.0+4194506

publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0+4
  cupertino_icons: ^1.0.8
  flutter_i18n: ^0.36.2
  sentry_flutter: ^9.4.0
  yivi_core:
    path: ../yivi_core

  face_verification:
    git:
      url: https://github.com/privacybydesign/vcmrtd.git
      ref: master
      path: face_verification

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # required by the integration tests (integration_test/)
  integration_test:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  rxdart: ^0.28.0
  mrz_parser:
    git:
      url: https://github.com/privacybydesign/mrz_parser
      ref: v3.0.0

flutter:
  uses-material-design: true
